version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - node -v
      - npm -v
artifacts:
  files:
    - '**/*'
  name: my-$(CODEBUILD_SOURCE_VERSION)-$(date +%Y-%m-%d) 
